// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraceSystem.Context;

namespace TraceSystem.Migrations
{
    [DbContext(typeof(HistoryContext))]
    [Migration("20220603021520_his")]
    partial class his
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25");

            modelBuilder.Entity("TraceSystem.Context.ItemNames", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CrateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ItemNamestb");
                });

            modelBuilder.Entity("TraceSystem.Context.ItemValues", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CrateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataVaue")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemNamesID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ItemNamesID");

                    b.ToTable("ItemValuestb");
                });

            modelBuilder.Entity("TraceSystem.Context.ItemValues", b =>
                {
                    b.HasOne("TraceSystem.Context.ItemNames", null)
                        .WithMany("ItemValue")
                        .HasForeignKey("ItemNamesID");
                });
#pragma warning restore 612, 618
        }
    }
}
